### ISSUE TITLE
有木有docker的部署方案呀？

### ISSUE THREAD

**Issue by ljq29** [engigu/Message-Push-Nest#8]
RTRT

**Comment by engigu** [comment]
正在制作中

**Comment by engigu** [comment]
https://github.com/engigu/Message-Push-Nest?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-

已经更新

**Comment by ljq29** [comment]
那个enable在第二次启动的时候不会覆盖数据库吗？如果不会的话，感觉这个参数要不要都无所谓吧，自动判断是否需要初始化就好了。
另外，能否compose里面增加上MySQL的语句？

**Comment by engigu** [comment]
那个enable是表字段新增的时候才会触发 ，只有第一次没有表的时候需要开启。后续如果项目新增了字段，也需要打开，代码会自动添加新字段。gorm的migrate只会在新增字段触发表结构数据变动，不用担心数据覆盖问题。
没有做初始化标识判断，是考虑到后续新加表字段。
目前第一次初始化后，关掉这个配置问题。

另外`能否compose里面增加上MySQL的语句`是指什么？表SQL，还是打印SQL

**Comment by ljq29** [comment]
比如：
```
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: <数据库名>
      MYSQL_USER: <用户名>
      MYSQL_PASSWORD: <密码>
      MYSQL_ROOT_PASSWORD: <root用户密码>
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
```
