### ISSUE TITLE
支持docker环境变量进行配置项目

### ISSUE THREAD

**Issue by engigu** [engigu/Message-Push-Nest#9]
比如：
```
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: <数据库名>
      MYSQL_USER: <用户名>
      MYSQL_PASSWORD: <密码>
      MYSQL_ROOT_PASSWORD: <root用户密码>
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
```

_Originally posted by @ljq29 in https://github.com/engigu/Message-Push-Nest/issues/8#issuecomment-1913492384_
